location:
   site_id: splk
   name: Sparkling Lake
   latitude: 46.008235   #Degrees North
   longitude: -89.699981  #Degrees East
da_setup:
    da_method: enkf
    par_fit_method: perturb_const
    ensemble_size:  31
    localization_distance: .na #distance in meters were covariances in the model error are used
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    use_obs_constraint: TRUE
    obs_filename: splk-targets-insitu.csv
model_settings:
   ncore: 4
   model_name: glm
   base_GLM_nml: glm3_splk.nml
   modeled_depths: [0.0,0.25,0.50,0.75,
                    1.00,1.25,1.50,1.75,
                    2.00,2.25,2.50,2.75,
                    3.00,3.25,3.50,3.75,
                    4.00,4.25,4.50,4.75,
                    5.00,5.25,5.50,5.75,
                    6.00,6.25,6.50,6.75,
                    7.00,7.25,7.50,7.75,
                    8.00,8.25,8.50,8.75,
                    9.00,9.25,9.50,9.75,
                    10.00,10.25,10.50,10.75,
                    11.00,11.25,11.50,11.75,
                    12.00,12.50,
                    13.00,13.50,
                    14.00,14.50,
                    15.00,15.50,
                    16.00,16.50,
                    17.00,17.50,
                    18.00,18.50,
                    19.00]
   par_config_file: parameter_calibration_config_splk.csv
   obs_config_file: observations_config_splk.csv
   states_config_file: states_config_splk.csv
   depth_model_sd_config_file: depth_model_sd_splk.csv
default_init:
   lake_depth: 19.2
   temp: [3.6, 3.5, 3.4, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3]
   temp_depths: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
   salinity: 0.0
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
inflow:
   include_inflow: FALSE
   use_forecasted_inflow: FALSE
   forecast_inflow_model: NA
   observed_filename: NA
   local_directory: NA
   use_ler_vars: FALSE
met:
   use_forecasted_met: TRUE
   use_observed_met: FALSE
   local_directory: .na
   observed_met_filename: .na
   use_ler_vars: FALSE
   forecast_lag_days: 1
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   inflow_process: TRUE
output_settings:
   diagnostics_names:  [extc]
   evaluate_past: FALSE
   variables_in_scores: [state, parameter, diagnostic]
