location:
   site_id: splk
   name: Sparkling Lake
   latitude: 46.008235   #Degrees North
   longitude: -89.699981  #Degrees East
da_setup:
    da_method: enkf
    par_fit_method: perturb_const
    ensemble_size:  31
    localization_distance: .na #distance in meters were covariances in the model error are used
    no_negative_states: TRUE
    assimilate_first_step: FALSE
    use_obs_constraint: TRUE
    obs_filename: splk-targets-insitu.csv
model_settings:
   ncore: 4
   model_name: glm
   base_GLM_nml: glm3_splk.nml
   modeled_depths:
   - 0.00
   - 0.50
   - 1.00
   - 1.50
   - 2.00
   - 2.50
   - 3.00
   - 3.50
   - 4.00
   - 4.50
   - 5.00
   - 5.50
   - 6.00
   - 6.50
   - 7.00
   - 7.50
   - 8.00
   - 8.50
   - 9.00
   - 9.50
   - 10.00
   - 10.50
   - 11.00
   - 11.50
   - 12.00
   - 12.50
   - 13.00
   - 13.50
   - 14.00
   - 14.50
   - 15.00
   - 15.50
   - 16.00
   - 16.50
   - 17.00
   - 17.50
   - 18.00
   par_config_file: parameter_calibration_config_splk.csv
   obs_config_file: observations_config_splk.csv
   states_config_file: states_config_splk.csv
   depth_model_sd_config_file: depth_model_sd_splk.csv
default_init:
   lake_depth: 9.4
   temp: [25.667, 24.9101, 23.067, 21.8815, 19.6658, 16.5739, 12.9292, 12.8456, 12.8127, 12.8079, 12.778]
   temp_depths: [0.127, 1.004, 2.005, 3.021, 4.002, 5.004, 6.004, 7.01, 8.001, 9.015, 9.518]
   salinity: 0.0
   snow_thickness: 0.0
   white_ice_thickness: 0.0
   blue_ice_thickness: 0.0
inflow:
   include_inflow: FALSE
   use_forecasted_inflow: FALSE
   forecast_inflow_model: NA
   observed_filename: NA
   local_directory: NA
   use_ler_vars: FALSE
met:
   use_forecasted_met: TRUE
   use_observed_met: FALSE
   local_directory: .na
   observed_met_filename: .na
   use_ler_vars: FALSE
   forecast_lag_days: 1
uncertainty:
   observation: TRUE
   process: TRUE
   weather: TRUE
   initial_condition: TRUE
   parameter: TRUE
   inflow_process: TRUE
output_settings:
   diagnostics_names:  [extc]
   evaluate_past: FALSE
   variables_in_scores: [state, parameter, diagnostic]
