restart_file: .na
start_datetime: 2023-05-20 00:00:00
end_datetime: .na
forecast_start_datetime: 2023-06-05 00:00:00
forecast_horizon: 16
sim_name: test
configure_flare: configure_flare_splk.yml
configure_obs: observation_processing_splk.yml
use_s3: FALSE

