restart_file: .na
start_datetime: 2022-09-28 11:00:00
end_datetime: .na
forecast_start_datetime: 2022-10-02 11:00:00
forecast_horizon: 16
sim_name: firstrun
configure_flare: configure_flare_splk.yml
configure_obs: observation_processing_splk.yml
use_s3: no
